### ISSUE TITLE
Preliminary grading with Cross Over team Review Ticket

### ISSUE THREAD

**Issue by BrianZhang2016** [BrianZhang2016/067#12]
[This Week's Tasks](https://github.com/BrianZhang2016/067/issues?q=is%3Aopen+is%3Aissue+label%3A%22Week+1+Project+Approval%22)
Brian Zhang: Github Admin
Zach Ye: Scrum Master
Leo Sun: Technical Officer and Deployment Manager
Stanley Yan: Primary Designer
[Wiki](https://github.com/BrianZhang2016/067/wiki)

**Comment by deimie** [comment]
Design - 1/1
Technicals - 1/1
Github - 1/1
Deployment - 1/1
Scrum Board - .75/1 Good scrum board content, but no wiki explaining scrum board plan

Total: 4.75/5
