### ISSUE TITLE
Brian's Review Ticket

### ISSUE THREAD

**Issue by BrianZhang2016** [BrianZhang2016/067#64]
# I would grade myself a 9.5/10. 
# Chase Ott's grade on me:  9.5 out of 10 (See comment below for more)

Individual/Pair Evaluation on Create Task Project - 5pts (1 point off)
- [x]  Wiki/Jekyll page with design ideas and usage
- [x]  Create Performance Task PBL feature
- [x]  Final committed program code showing algorithms written in JS/Python
- [x]  Written responses to all the prompts in the performance task
- [x]  1min video that meets CB create task requirements 

Team Final Grading Considerations - 5 pts (0.5 point off)
PBL Github pages. Jekyll, WIKI, live review focus
- [x]  PBL theme consistent through project and described in Github Pages
- [x]  Sassy / Bootstrap
- [x]  Blueprint illustration/demonstration
- [x]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch
- [x]  Individual PBL MVC feature/commits showing algorithms written in JS/Python 

[Week 11](https://youtu.be/alDoa2L-KWc) (Part of Team Final Grading Considerations (0.5 point off))

- [x]  Highlight of best features
- [x]  CRUD/Search on project database tables, easy to identify from UI
- [x]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)
- [ ]  Google Search or Google translate implemented 
- [x]  Scrum Board - Overview of completed tasks and Github tangibles

**Comment by ChaseOtt** [comment]
Brian did his wiki page on his create task that detailed his plan for his Simon says create task
He did his create task which met the college board standards for the create task
He has his create task committed and working written in java script
Detailed written response that describes his create task
He made the 1 minute video that is on his wiki showing his program
Their team's theme is decently consistent throughout their website
They have Bootstrap on many of their pages 
They have blueprints to organize their python files 
Their CRUD database works and you can search through it as well as add new items.
Brian has his individual MVC feature 
His team video highlights cool features that are on his website
They showed their CRUD database in the Video
They didn't have google search or google translate
They showed the scrum board that detailed all their work in the last tri

<h> I believe Brian should have an 9.5 out of 10 </h>
His team is missing the search or translation
