### ISSUE TITLE
Leo's Review Ticket

### ISSUE THREAD

**Issue by BrianZhang2016** [BrianZhang2016/067#65]
# My partner (William Wu) graded me a 9.3/10.
# I graded myself a 9.5/10.
Individual/Pair Evaluation on Create Task Project - 5pts
- [x]  Wiki/Jekyll page with design ideas and usage
- [x]  Create Performance Task PBL feature
- [x]  Final committed program code showing algorithms written in JS/Python
- [x]  Written responses to all the prompts in the performance task
- [x]  1min video that meets CB create task requirements 
Team Final Grading Considerations - 5 pts
PBL Github pages. Jekyll, WIKI, live review focus
- [x]  PBL theme consistent through project and described in Github Pages
- [x]  Sassy / Bootstrap
- [x]  Blueprint illustration/demonstration
- [x]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch
- [x]  Individual PBL MVC feature/commits showing algorithms written in JS/Python 

[Week 11](https://youtu.be/alDoa2L-KWc) (Part of Team Final Grading Considerations (0.5 point off))

- [x]  Highlight of best features
- [x]  CRUD/Search on project database tables, easy to identify from UI
- [x]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)
- [ ]  Google Search or Google translate implemented (no google search or google translate -0.5)
- [x]  Scrum Board - Overview of completed tasks and Github tangibles

**Comment by willcyber** [comment]
Individual/Pair Evaluation on Create Task Project - 5pts **(0,1 pt off)**
- [x]  Wiki/Jekyll page with design ideas and usage
- [ ]  Create Performance Task PBL feature  (no user interface -0.1)
- [x]  Final committed program code showing algorithms written in JS/Python
- [x]  Written responses to all the prompts in the performance task
- [x]  1min video that meets CB create task requirements

Team Final Grading Considerations - 5 pts **(0.1 pt off )**
PBL Github pages. Jekyll, WIKI, live review focus
- [ ]  PBL theme consistent through project and described in Github Pages (they have CSS and base.html that keeps a consistent theme, but theme isn't very organized -0.1)
- [x]  Sassy / Bootstrap (dark mode)
- [x]  Blueprint illustration/demonstration (blueprint in crud)
- [x]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch
- [x]  Individual PBL MVC feature/commits showing algorithms written in JS/Python (create task meets the requirements)

[Week 11](https://youtu.be/alDoa2L-KWc) (Part of Team Final Grading Considerations **(0.5 point off))**
- [x]  Highlight of best features
- [x]  CRUD/Search on project database tables, easy to identify from UI
- [x]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions) 
- [ ]  Google Search or Google translate implemented (missing from video -0.5)
- [x]  Scrum Board - Overview of completed tasks and Github tangibles

**Final score - 9.3/10**
