### ISSUE TITLE
Zach's Review Ticket

### ISSUE THREAD

**Issue by BrianZhang2016** [BrianZhang2016/067#66]
PEER GRADE (Partner Michael Chen): 9.7/10

Individual Grade: 9.5/10

Individual/Pair Evaluation on Create Task Project - 5pts
- [ ]  Wiki/Jekyll page with design ideas and usage: I have all required Wiki Pages as well as Jekyll pages as seen on the README. 1/1
- [ ]  Create Performance Task PBL feature: My create task program is related to the PBL and I also made sure to satisfy all of the college board requirements. 1/1
- [ ]  Final committed program code showing algorithms written in JS/Python: There are algorithms that we have did in class in my final committed code, which runs and preforms correctly. 1/1
- [ ]  Written responses to all the prompts in the performance task: I completed all of the written responses for the performance task, all of them meet the college board requirements and all draw near to the recommended length. 1/1
- [ ]  1min video that meets CB create task requirements: My video meets all college board requirements, which include time as well as displaying input, output, and program purpose. 1/1

Team Final Grading Considerations - 5 pts
PBL Github pages. Jekyll, WIKI, live review focus
- [ ]  PBL theme consistent through project and described in Github Pages: The PBL theme is seen throughout the entire website, as many of the backgrounds and colors are related to the PBL, and this is well described in the Github pages. 0.5/0.5
- [ ]  Sassy / Bootstrap: Utilized bootstrap as well as sassy across the website. This can be specifically seen in the review pages, which use bootstrap on the buttons page. 0.5/0.5
- [ ]  Blueprint illustration/demonstration: Blueprints are completed and are used in the aboutus.py. 0.5/0.5
- [ ]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch: CRUD is completed is running correctly. However we did not use it on any other part of the website. 0.3/0.5
- [ ]  Individual PBL MVC feature/commits showing algorithms written in JS/Python: The Individual PBL MVC feature is seen in our Create Task program. 0.5/0.5

[Week 11](https://youtu.be/alDoa2L-KWc) (Part of Team Final Grading Considerations (0.5 point off))

- [ ]  Highlight of best features: Best features show time spent as well as usefulness. 0.4/0.5 
- [ ]  CRUD/Search on project database tables, easy to identify from UI: The crud as well as search are in obvious places and are running well. 0.5/0.5
- [ ]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions): MVC is utilized in many places across the website, one example is the create task as well as the API's. 0.5/0.5
- [ ]  Google Search or Google translate implemented: Google search was attempted but was not able to run correctly. 0.2/0.5
- [ ]  Scrum Board - Overview of completed tasks and Github tangibles: The scrumboard is well organized and all the weeks as well as specific issues are easy to find. 0.5/0.5

**Comment by Michaelc179** [comment]
9.7 POINTS

Individual - Zach Ye

- [x] Jekyll page that describes how the website is for movie reviews
- [x] Page of TV Shows with toggle features, reviews for shows and movies
- [x] Code is mostly written in JS, and some use of Python.
- [x] Written responses to [Performance Task](https://github.com/BrianZhang2016/067/wiki/Create-Task-Written-Responses-Zachary-Ye) and how his code fulfills all the College Board requirements for the Create Task
- [x] 1 minute video displaying the website's design and how the task relates to CB requirements.

Team

- [x] PBL theme of a movie/TV show review site, is described in Github Pages
- [x] Bootstrap is used to format the review pages on the website
- [ ] Blueprints in the python, aboutus.py file for each about us page, however the other pages (such as review) do not use blueprints (-0.1)
- [ ] Async Crud Database - however there are no major PBL features relating to the DB (-0.1)
- [x] MVC/PBL features are all in JS and python

Week 11

- [x]  Features are all highlighted very well, I know exactly what the website is about and how to use the website properly
- [x]  CRUD/Search works properly on the database tables, even though they are not directly related to PBL
- [x]  MVC - a code overview showing usage of MVC in the database and search functions
- [ ]  Google Search or Google translate is not fully implemented in runtime, but is attempted in the code (-0.1)
- [x]  Scrum Board - Overview of completed tasks and Github tangibles

REVIEWER - Michael Chen
