### ISSUE TITLE
Stanley's Review Ticket

### ISSUE THREAD

**Issue by BrianZhang2016** [BrianZhang2016/067#67]
# My partner (Byron Lu) graded me a 9.5/10.
# I graded myself a 9.5/10.

Individual/Pair Evaluation on Create Task Project - 5pts
- [ ]  Wiki/Jekyll page with design ideas and usage
- [ ]  Create Performance Task PBL feature
- [ ]  Final committed program code showing algorithms written in JS/Python
- [ ]  Written responses to all the prompts in the performance task
- [ ]  1min video that meets CB create task requirements 

Team Final Grading Considerations - 5 pts
PBL Github pages. Jekyll, WIKI, live review focus
- [ ]  PBL theme consistent through project and described in Github Pages
- [ ]  Sassy / Bootstrap
- [ ]  Blueprint illustration/demonstration
- [ ]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch
- [ ]  Individual PBL MVC feature/commits showing algorithms written in JS/Python 

[Week 11](https://youtu.be/alDoa2L-KWc) (Part of Team Final Grading Considerations (0.5 point off))

- [ ]  Highlight of best features
- [ ]  CRUD/Search on project database tables, easy to identify from UI
- [ ]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)
- [ ]  Google Search or Google translate implemented 
- [ ]  Scrum Board - Overview of completed tasks and Github tangibles

**Comment by byronlu06** [comment]
Individual/Pair Evaluation on Create Task Project - 5pts
- [x]  Wiki/Jekyll page with design ideas and usage
- [ ]  Create Performance Task PBL feature
- .25 no user interface, only  visible in python terminal
- [x]  Final committed program code showing algorithms written in JS/Python
- [x]  Written responses to all the prompts in the performance task
- [x]  1min video that meets CB create task requirements
Team Final Grading Considerations - 5 pts
PBL Github pages. Jekyll, WIKI, live review focus
- [x]  PBL theme consistent through project and described in Github Pages
- [x]  Sassy / Bootstrap
- [x]  Blueprint illustration/demonstration
- -0.25 blueprints for about us pages, but other pages are still all in main.py and don't have their own blueprint
- [x]  CRUD Async Operation - runtime and understanding of JavaScript and Fetch
- [x]  Individual PBL MVC feature/commits showing algorithms written in JS/Python
- [x]  Highlight of best features
- [x]  CRUD/Search on project database tables, easy to identify from UI
- [x]  MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)
- [x]  Google Search or Google translate implemented
- [x]  Scrum Board - Overview of completed tasks and Github tangibles

9.5/10
